spring:
  application:
    name: siscompras
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/compras
    username: compras
    password: compras
    hikari:
      auto-commit: false
  jackson:
    date-format: yyyy-MM-dd
    deserialization:
      fail-on-unknown-properties: false
  jpa:
    #    database-platform: io.github.jhipster.domain.util.FixedPostgreSQL95Dialect
    database: POSTGRESQL
    show-sql: true
    open-in-view: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.enable_lazy_load_no_trans: true
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
server:
  port: 8080

application:
  feign:
    pagamento: http://localhost:8082
    estoque: http://localhost:8081

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui.html